In [16]:
feature = open ("/Users/ddyihai/Desktop/232e/project2/Project2/mldata/trainwhole_nodeid.txt",'r')
#feature2 = open ("/Users/ddyihai/Desktop/232e/project2/Project2/mldata/train3w_nodeid.txt",'r')
label = open ("/Users/ddyihai/Desktop/232e/project2/Project2/mldata/labelwhole_nodeid.txt",'r')
#label2 = open ("/Users/ddyihai/Desktop/232e/project2/Project2/mldata/label3w_nodeid.txt",'r')
test_feature = open ("/Users/ddyihai/Desktop/232e/project2/Project2/mldata/tests.txt",'r')

In [17]:

print "Create movie_direct_map"
i=1
feature_line = []
for line in feature.readlines():
    line = line[:]
    tmp=line.split(" ")
    tmp_line = [float(tmp[i]) for i in range (106)]
    feature_line.append(tmp_line)
#for line in feature2.readlines():
#    line = line[:]
#    tmp=line.split(" ")
#    tmp_line = [float(tmp[i]) for i in range (106)]
#    feature_line.append(tmp_line)
    
    
feature_test = []
for line in test_feature.readlines():
    line = line[:]
    tmp=line.split(" ")
    tmp_line = [float(tmp[i]) for i in range (106)]
    feature_test.append(tmp_line[100:])
    
    
label_line = []
for line in label.readlines():
    tmp=line.split(" ")
    label_line.append(float(tmp[0]))
#for line in label2.readlines():
#    label_line.append(float(line))

Create movie_direct_map


In [91]:
print(len(label_line))
print(len(feature_line[1]))
print(feature_line[2][101:])
print(feature_line[30][0:101])
print(label_line[2])
print(len(feature_line))
print(len(label_line))

29551
106
[1.870895e-05, 1.864647e-05, 1.819834e-05, 1.814195e-05, 1.80014e-05]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
3.7
29551
29551


In [19]:
feature = []
label = []
n=0
for i in range (len(label_line)):
    if(label_line[i] != 0.0):
        n=n+1
        feature.append(feature_line[i][100:])
        label.append(label_line[i])

In [20]:
#Linear Regression
from sklearn import linear_model
from sklearn import cross_validation
from sklearn.metrics import mean_squared_error
import numpy as np
regr = linear_model.LinearRegression(normalize = True)
regr.fit(feature, label)
res = regr.predict(feature_test)
res

array([ 6.1375217 ,  6.14992907,  6.23478102])

In [21]:
#model_score = cross_validation.cross_val_score(regr, feature, label, cv=10, scoring='mean_squared_error')
#model_score
cross_mse = []
for i in range (10):
    X_train, X_test, y_train, y_test = cross_validation.train_test_split(feature, label, test_size=0.1, random_state=i)
    clf = linear_model.LinearRegression()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)   
    count = 0
    for i in range (len(y_pred)):
        if(y_pred[i]>10):
            count = count+1
            y_pred[i] = 10
        if(y_pred[i]<0):
            count = count+1
            y_pred[i]=0
    print(count,len(y_pred))
    cross_mse.append((mean_squared_error(y_pred,y_test))**0.5)
    

print(sum(cross_mse)/10)
cross_mse


(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
1.27922350746


[1.2680402041612517,
 1.2822356862809463,
 1.2715193562977336,
 1.2649707538185422,
 1.2744562038949301,
 1.3065576863102728,
 1.2504238213017691,
 1.2873042902210039,
 1.2713536504510441,
 1.3153734218510649]

In [22]:
#SVM
import numpy as np
from sklearn.svm import LinearSVR
clf = LinearSVR()
clf.fit(feature,label)
res = clf.predict(feature_test)
print(res)

[ 6.20000226  6.20000304  6.20000403]


In [23]:
#model_score = cross_validation.cross_val_score(regr, feature, label, cv=10, scoring='mean_squared_error')
#model_score
cross_mse = []
for i in range (10):
    X_train, X_test, y_train, y_test = cross_validation.train_test_split(feature, label, test_size=0.1, random_state=i)
    clf = LinearSVR()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)   
    count = 0
    for i in range (len(y_pred)):
        if(y_pred[i]>10):
            count = count+1
            y_pred[i] = 10
        if(y_pred[i]<0):
            count = count+1
            y_pred[i]=0
    print(count,len(y_pred))
    cross_mse.append((mean_squared_error(y_pred,y_test))**0.5)
    

print(sum(cross_mse)/10)
cross_mse


(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
1.28750207162


[1.2775719925369138,
 1.2911690698946858,
 1.2810310447090487,
 1.2714032529869619,
 1.284111185684317,
 1.3172867772120755,
 1.2502050659961625,
 1.2964047380515968,
 1.2817965425780276,
 1.3240410465286683]

In [24]:
print(len(y_pred))
sumy = 0
s=len(y_pred)
for i in range (s):
    if(y_pred[i] > 10):
        print(y_test[i])
    sumy = sumy + (y_pred[i]-y_test[i])* (y_pred[i]-y_test[i])

2956


In [25]:
from sklearn.ensemble import AdaBoostRegressor
cross_mse = []
for i in range (10):
    X_train, X_test, y_train, y_test = cross_validation.train_test_split(feature, label, test_size=0.1, random_state=i)
    clf = AdaBoostRegressor(n_estimators=2)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)   
    count = 0
    for i in range (len(y_pred)):
        if(y_pred[i]>10):
            count = count+1
            y_pred[i] = 10
        if(y_pred[i]<0):
            count = count+1
            y_pred[i]=0
    print(count,len(y_pred))
    cross_mse.append((mean_squared_error(y_pred,y_test))**0.5)
print(sum(cross_mse)/len(cross_mse))
cross_mse

(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
(0, 2956)
1.27598017668


[1.2649529555602435,
 1.2800230116330777,
 1.2695157266261226,
 1.2615088188448789,
 1.2706758515176624,
 1.3005471878203612,
 1.2490580888872769,
 1.2880644521338782,
 1.2659386225993081,
 1.3095170511947816]

In [14]:
clf = AdaBoostRegressor(n_estimators=100)
clf.fit(feature, label)
res = clf.predict(feature_test)
res

array([ 6.00323213,  6.18899676,  6.36407625])

7.4

6

In [56]:
from numpy import transpose
from numpy import dot
X = transpose(np.asarray(feature))
Y = np.asarray(label)
import numpy
print numpy.corrcoef(X,Y)


[[ 1.          0.07845974  0.08669426  0.09024382  0.09522026  0.09599275
   0.06897256]
 [ 0.07845974  1.          0.86879065  0.8202101   0.78770321  0.76578452
   0.03462383]
 [ 0.08669426  0.86879065  1.          0.95113834  0.92062883  0.89796112
   0.04644653]
 [ 0.09024382  0.8202101   0.95113834  1.          0.97082695  0.94899323
   0.04758647]
 [ 0.09522026  0.78770321  0.92062883  0.97082695  1.          0.97938325
   0.04865148]
 [ 0.09599275  0.76578452  0.89796112  0.94899323  0.97938325  1.
   0.0501453 ]
 [ 0.06897256  0.03462383  0.04644653  0.04758647  0.04865148  0.0501453
   1.        ]]


In [88]:

for i in range (6):
    tmp_feature = []
    for j in range (len(label)):
        tmp_feature.append(feature[j][i])
    X = np.asarray(tmp_feature)
    Y = transpose(np.asarray(label))
    numerator = Y.dot(X) - (sum(X) * sum(Y))/len(X); 
    Denominator = ((transpose(X).dot(X) - sum(X)**2 / len(X)) * (Y.dot(transpose(Y)) - sum(Y)**2 / len(X)))*0.5
    print(i)
    print(numerator)
    print(Denominator)
    coeff = numerator / Denominator
    print(coeff)

SyntaxError: invalid syntax (<ipython-input-88-401adbefa47a>, line 3)

In [93]:
count = 0
for j in range (len(label)):
    if(feature[j][0] == 1.0):
        count = count+1
print(count)

296


In [ ]:
coeff = numerator / Denominator;  